name: lab_3
description: Mobile Information Systems - Laboratory Exercise 3

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  syncfusion_flutter_calendar:
  flutter_session_manager: ^1.0.3
  flutter_lints: ^2.0.0
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.0
  rxdart: ^0.27.4
  geolocator: ^9.0.2
  google_maps_flutter: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true